AllCops:
  Exclude:
    - vendor/**/*

Naming/MethodName:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'lib/strava-ruby-client.rb'

Style/ModuleFunction:
  EnforcedStyle: extend_self

Style/Documentation:
  Enabled: false

inherit_from: .rubocop_todo.yml
